const path = require('path')
const WexExtManifestPlugin = require('./lib/WexExtManifestPlugin')

module.exports = (opts = {}) => neutrino => {
  const options = {
    polyfill: false,
    template: path.resolve(__dirname, 'template.ejs'),
    manifest: path.resolve(neutrino.options.root, 'src', 'manifest'),
    ...opts
  }

  if (!path.isAbsolute(options.manifest)) {
    options.manifest = path.resolve(neutrino.options.root, options.manifest)
  }

  Object.entries(neutrino.options.mains).forEach(([name, { webext }]) => {
    if (
      webext &&
      webext.type &&
      /^(content_scripts|background|pageless)$/.test(webext.type)
    ) {
      // remove plugins generated by web preset
      neutrino.config.plugins.delete(`html-${name}`)
      return
    }

    if (options.polyfill) {
      neutrino.config.plugin(`html-${name}`).tap(args => {
        if (args[0]) {
          args[0].webextPolyfill = options.polyfill
          args[0].template = options.template
        }
        return args
      })
    }
  })

  neutrino.config
    .plugin('webext')
    .use(WexExtManifestPlugin, [options, neutrino])
}
