const path = require('path')
const WexExtManifestPlugin = require('./WexExtManifestPlugin')

module.exports = (opts = {}) => neutrino => {
  const argv = require('yargs-parser')(process.argv.slice(2))
  const isDev = process.env.NODE_ENV === 'development'
  const isProd = process.env.NODE_ENV === 'production'

  const options = {
    polyfill: false,
    template: path.resolve(__dirname, '../template.ejs'),
    manifest: path.resolve(neutrino.options.root, 'src', 'manifest'),
    setup: '',
    ...opts
  }

  ;['template', 'manifest', 'setup'].forEach(key => {
    if (options[key] && !path.isAbsolute(options[key])) {
      options[key] = path.resolve(neutrino.options.root, options[key])
    }
  })

  const backgroundEntry = Object.keys(neutrino.options.mains).find(name => {
    const { webext } = neutrino.options.mains[name]
    return webext && webext.type === 'background'
  })

  Object.entries(neutrino.options.mains).forEach(([name, { webext }]) => {
    if (isProd) {
      if (
        webext &&
        webext.type &&
        /^(content_scripts|background|pageless)$/.test(webext.type)
      ) {
        // remove plugins generated by web preset
        neutrino.config.plugins.delete(`html-${name}`)
        return
      }

      if (options.polyfill) {
        neutrino.config.plugin(`html-${name}`).tap(args => {
          if (args[0]) {
            args[0].webextPolyfill = options.polyfill
            args[0].template = options.template
          }
          return args
        })
      }
    }

    if (isDev) {
      // if you want to keep all the entries but open to a specific path
      // use webpack-dev-server cli option --open-page [entry name].html
      if (
        name !== backgroundEntry &&
        argv.wextentry &&
        argv.wextentry !== name
      ) {
        neutrino.config.entryPoints.delete(name)
        neutrino.config.plugins.delete(`html-${name}`)
        return
      }

      const isBackground = backgroundEntry === name

      neutrino.config
        .entry(name)
        .when(webext && webext.setup, config =>
          config.prepend(
            path.isAbsolute(webext.setup)
              ? webext.setup
              : path.resolve(neutrino.options.source, webext.setup)
          )
        )
        .when(options.polyfill, config =>
          config.prepend('webextension-polyfill')
        )
        .when(options.setup, config => config.prepend(options.setup))
        .prepend(
          require.resolve(
            `webextensions-emulator/dist/${
              isBackground ? 'background' : 'core'
            }`
          )
        )
        .end()
        .when(
          isBackground,
          config => config.plugins.delete(`html-${name}`),
          config => {
            if (backgroundEntry) {
              // load background with other entries
              config.plugin(`html-${name}`).tap(args => {
                if (args[0]) {
                  args[0].inject = false // manual inject
                  args[0].webextBackground = backgroundEntry
                  args[0].chunks.push(backgroundEntry)
                  args[0].template = path.resolve(
                    __dirname,
                    '../template.dev.ejs'
                  )
                }
                return args
              })
            }
          }
        )
    }
  })

  if (isDev) {
    const entry = argv.wextentry
      ? argv.wextentry
      : Object.keys(neutrino.options.mains).find(
        entry => entry !== backgroundEntry
      )
    neutrino.config.optimization
      .clear()
      .end()
      .devServer.index(`${entry}.html`)
  }

  if (isProd) {
    neutrino.config
      .plugin('webext')
      .use(WexExtManifestPlugin, [options, neutrino.options])
  }

  if (neutrino.config.module.rules.has('lint')) {
    neutrino.config.module
      .rule('lint')
      .use('eslint')
      .tap(options => {
        if (!options.globals) {
          options.globals = ['browser']
        } else if (options.globals.length != null) {
          options.globals.push('browser')
        } else {
          options.globals.browser = true
        }
        return options
      })
  }
}
